#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : thrift
Version  : 0.9.3
Release  : 17
URL      : https://pypi.python.org/packages/source/t/thrift/thrift-0.9.3.tar.gz
Source0  : https://pypi.python.org/packages/source/t/thrift/thrift-0.9.3.tar.gz
Summary  : Python bindings for the Apache Thrift RPC system
Group    : Development/Tools
License  : Apache-2.0
Requires: thrift-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : setuptools

%description
No detailed description available

%package python
Summary: python components for the thrift package.
Group: Default

%description python
python components for the thrift package.


%prep
%setup -q -n thrift-0.9.3

%build
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
